### ISSUE TITLE
Don't format comma after last item / property / map entry

### ISSUE THREAD

**Issue by novemberborn** [novemberborn/kathryn#18]
Or at least make this configurable.

**Comment by novemberborn** [comment]
@sindresorhus I'm not sure this is feasible. It's reasonably easy to set a flag when a [list item](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/complexValues/object.js#L115), [iterable item](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/complexValues/object.js#L157), [property](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/complexValues/object.js#L98) or [map entry](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/complexValues/map.js#L61) is the latest. The difficulty arises with more specialized descriptors.

For example the `Error` descriptor [discards enumerable `name` properties](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/complexValues/error.js#L104), and [always emits`message` properties](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/complexValues/error.js#L111). It would have to buffer all properties and then rewrite the `last` flag on one of them, which is unnecessary work when comparisons are performed, as well as being a little icky.

It also complicates the custom diff formatting logic that is used for (string) [properties](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/metaDescriptors/property.js#L182), [items](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/metaDescriptors/item.js#L184) and [map entry values](https://github.com/novemberborn/kathryn/blob/8eb9589c4bcdaa5282e50f1428f8ba2302e7fc3a/lib/metaDescriptors/mapEntry.js#L176).

> Having a trailing comma is distracting and makes the output more noisy.

Perhaps when there's only one item, but not necessarily when there are multiple items. There's also less diff churn which can be nice for snapshots. I don't think it's worth the overhead in Kathryn itself, nor the complexity imposed on plugin authors.

**Comment by sindresorhus** [comment]
Ok. Let's close this for now and revisit sometime in the future. Not that important. I bet we'll get requests for this though.
